export const API_ENDPOINTS = {
  LOGIN: `/api/v1/login`,
  REGISTER_ORGANISATION: `/api/v1/registration/organisation`,
  REGISTER_VOLUNTEER: `/api/v1/registration/volunteer`,
  VOLUNTEER_PROFILE: `/api/v1/volunteer/my_profile`,
  ORGANISATION_PROFILE: `/api/v1/organisation/my_profile`,
  UPDATE_VOLUNTEER_PROFILE: `/api/v1/update/volunteer`,
  UPDATE_ORGANISATION_PROFILE: `/api/v1/update/organisation`,
  UPLOAD_VOLUNTEER_AVATAR: `/api/v1/upload/avatar/volunteer`,
  UPLOAD_ORGANISATION_AVATAR: `/api/v1/upload/avatar/organisation`,
  UPLOAD_ACTIVITY_COVER_IMAGE: '/api/v1/upload/activity/cover',
  UPLOAD_ACTIVITY_GALLERY_IMAGES: '/api/v1/upload/activity/gallery_images',
  CHANGE_PASSWORD: `/api/v1/change_password`,
  CREATE_ACTIVITY: `/api/v1/organisation/add_activity`,
  JOIN_ACTIVITY: `/api/v1/volunteer/enter_to_activity?id=`,
  LEAVE_ACTIVITY: `/api/v1/volunteer/leave_activity?id=`,
  IS_VOLUNTEER_JOINED: `/api/v1/volunteer/is_my_activity?activityId=`,
  DELETE_ACTIVITY: '/api/v1/organisation/delete_activity/',
  GET_ALL_SUBSCRIPTIONS: '/api/v1/notifications/my_subscriptions',
  SUBSCRIBE_TO_ORGANISATION: '/api/v1/notifications/subscribe',
  UNSUBSCRIBE_FROM_ORGANISATION: '/api/v1/notifications/unsubscribe',
  GET_AVERAGE_RATING_OF_ORGANISATION: '/api/v1/organisations/average-rating/',
  RATE_ORGANISATION: '/api/v1/organisations/rate/',
  POST_FEEDBACK: '/api/v1/organisations/feedback/give_feedback',
};
